<h1 style="color: blue; text :bold; align:center;" >Numpy-py</h1>

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
c=np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
x=np.arange(0,100,1) # range of values in array (startval ,endval,step)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [9]:
y=np.linspace(0,10,5)#set of values by interval (start,end,no.of values equalInterval)
print(y)

[ 0.   2.5  5.   7.5 10. ]


### Array Properties

In [19]:
p=np.array([5,6,7,8,9,10]) #single dimension
q=np.array([(1,2,3,4,5,6),(7,8,9,10,11,12)]) #two dimensions
print(q.ndim)# number of dimensions
print(q.shape)# shape of array (rows and columns)
print(p.size)# total number of elements
print(q)
print(q.T)# transpose
print(q.T.shape)


2
(2, 6)
6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
(6, 2)


### Array reshape

In [21]:
q=q.reshape(6,2) #(rows,columns,channels)
q

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### Array Slicing

In [24]:
r=np.array([(1,23,44,5),(2,3,4,6)])
print(r)
print(r[0,1])# splicing rows and columns
print(r[0:,2]) # splicing rows and columns

[[ 1 23 44  5]
 [ 2  3  4  6]]
23
[44  4]


### Array Value Operations

In [25]:
s=np.array([1,2,3,4,5,6,7,8,9,10])
print(s.min())
print(s.max())
print(s.mean())
print(s.std())
print(s.shape)
print(s.size)
print(s.ndim)
print(s.tolist())
print(s.reshape(5,2))
print(s.reshape(5,2).tolist())
print(s.reshape(5,2).sum())
print(s.reshape(5,2).mean())
print(s.reshape(5,2).std())
print(s.reshape(5,2).var())
print(s.reshape(5,2).argmax())

1
10
5.5
2.8722813232690143
(10,)
10
1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
55
5.5
2.8722813232690143
8.25
9


### Array arithmetic operations

In [26]:
m=np.array([23,45,56,65])
n=np.array([1,2,3,4])
print(m+n)
print(m-n)
print(m*n)
print(m/n)
print(m**n)
print(m%n)
print(m//n)

[24 47 59 69]
[22 43 53 61]
[ 23  90 168 260]
[23.         22.5        18.66666667 16.25      ]
[      23     2025   175616 17850625]
[0 1 2 1]
[23 22 18 16]


In [ ]:
m=np.array([23,45,56,65])
n=np.array([(1,2,3,4),(9,8,7,6)])
print(n.sum(axis=0)) #sum of each row
print(n.sum(axis=1)) #sum of each column

[10 10 10 10]
[10 30]


In [31]:
n=np.array([(1,2,3,4),(9,8,7,6)])
o=np.array([(11,12,13,14),(19,18,17,16)])
print(np.vstack((n,o))) # vertical stacking
print(np.hstack((n,o))) # horizontal stacking
print(np.concatenate((n,o))) # concatenation
print(np.ravel(n)) # flattening

[[ 1  2  3  4]
 [ 9  8  7  6]
 [11 12 13 14]
 [19 18 17 16]]
[[ 1  2  3  4 11 12 13 14]
 [ 9  8  7  6 19 18 17 16]]
[[ 1  2  3  4]
 [ 9  8  7  6]
 [11 12 13 14]
 [19 18 17 16]]
[1 2 3 4 9 8 7 6]
